---

- name: Restart timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted

- name: Save iptables rule
  shell: /usr/sbin/netfilter-persistent save

- name: Stop SSM
  systemd: 
    name: amazon-ssm-agent
    state: stop

- name: Start SSM
  systemd:
    name: amazon-ssm-agent
    state: started
